package_assets: on # (on, off, always)
embed_assets: on # (on, off, datauri)
compress_assets: on # (on, off)
gzip_assets: on # (on, off)

javascripts:
  js:
    - public/javascripts/*.js
    - public/javascripts/mxn/mxn-min.js
    - public/javascripts/mxn/mxn.core-min.js
    - public/javascripts/mxn/mxn.googlev3.core-min.js


stylesheets:
  common:
    - public/stylesheets/blueprint/screen.css
    - public/stylesheets/*.css

